name: Build Package

on:
  workflow_call:

env:
  APP_NAME: system-info

jobs:
  build_windows:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
          - runner: windows-latest
            target: x86_64-pc-windows-msvc
            label: windows-x86_64

    steps:
      - name: 检出仓库
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: 设置 rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform.target }}

      - name: 设置 rust 缓存
        uses: swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1 # v2.8.1
        with:
          prefix-key: ${{ env.APP_NAME }}

      - name: 配置 pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        with:
          version: 10.22.0

      - name: 构建
        run: |
          pnpm install
          pnpm build --target ${{ matrix.platform.target }}
        working-directory: system_info_node

      - name: 上传构建产物
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5
        with:
          name: "${{ env.APP_NAME }}-node-${{ matrix.platform.label }}"
          path: |
            system_info_node/dist/${{ env.APP_NAME }}*.node

  build_macos:
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        platform:
          - runner: macos-latest
            target: x86_64-apple-darwin
            label: macos-x86_64
          - runner: macos-latest
            target: aarch64-apple-darwin
            label: macos-aarch64

    steps:
      - name: 检出仓库
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: 设置 rust
        uses: dtolnay/rust-toolchain@stable

      - name: 添加目标平台
        run: |
          rustup target add ${{ matrix.platform.target }}

      - name: 设置 rust 缓存
        uses: swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1 # v2.8.1
        with:
          prefix-key: ${{ env.APP_NAME }}

      - name: 配置 pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        with:
          version: 10.22.0

      - name: 构建
        run: |
          pnpm install
          pnpm build --target ${{ matrix.platform.target }}
        working-directory: system_info_node

      - name: 上传构建产物
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5
        with:
          name: "${{ env.APP_NAME }}-node-${{ matrix.platform.label }}"
          path: |
            system_info_node/dist/${{ env.APP_NAME }}*.node

  build_linux:
    runs-on: ${{ matrix.platform.runner }}
    container: ${{ matrix.platform.container }}
    strategy:
      matrix:
        platform:
          - runner: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            label: linux-x86_64
          - runner: ubuntu-24.04-arm
            target: aarch64-unknown-linux-gnu
            label: linux-aarch64

    steps:
      - name: 检出仓库
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0

      - name: 设置 rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform.target }}

      - name: 设置 rust 缓存
        uses: swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1 # v2.8.1
        with:
          prefix-key: ${{ env.APP_NAME }}

      - name: 配置 pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        with:
          version: 10.22.0

      - name: 设置apt 包
        uses: awalsh128/cache-apt-pkgs-action@acb598e5ddbc6f68a970c5da0688d2f3a9f04d05 # v1.6.0
        with:
          packages: libdrm-dev libdrm-amdgpu1

      - name: 构建
        run: |
          pnpm install
          pnpm build --target ${{ matrix.platform.target }}
        working-directory: system_info_node

      - name: 上传构建产物
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5
        with:
          name: "${{ env.APP_NAME }}-node-${{ matrix.platform.label }}"
          path: |
            system_info_node/dist/${{ env.APP_NAME }}*.node


      - name: 上传npm包
        if: matrix.platform.label == 'linux-x86_64'
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5
        with:
          name: "npm-package"
          path: |
            system_info_node/dist/index.js
            system_info_node/dist/index.d.ts
            system_info_node/package.json