name: release
on:
  push:
    branches:
      - main
  pull_request_target:
    branches-ignore:
      - 'release-please**'
  workflow_dispatch:

permissions:
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  release:
    if: "!startsWith(github.head_ref, 'release-please')"
    runs-on: ubuntu-latest
    outputs:
      core: ${{ steps.release-please.outputs['system_info_core--release_created'] }}
      node: ${{ steps.release-please.outputs['system_info_node--release_created'] }}
      node_tag_name: ${{ steps.release-please.outputs['system_info_node--tag_name'] }}
    steps:
      - name: 获取token
        uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2.1.4
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: 运行 release-please-action
        id: release-please
        uses: googleapis/release-please-action@16a9c90856f42705d54a6fda1823352bdc62cf38 # v4.4.0
        with:
          token: ${{ steps.app-token.outputs.token }}
          config-file: .release-please-config.json
          manifest-file: .release-please-manifest.json

  test:
    if: "!startsWith(github.head_ref, 'release-please')"
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          ref: ${{ github.event.pull_request.head.ref || github.ref_name }}
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}

      - name: 设置 Rust 工具链
        uses: dtolnay/rust-toolchain@stable

      - name: 设置 Rust 缓存
        uses: swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1 # v2.8.1
        with:
          prefix-key: 'system_info'

      - name: 设置apt 包
        uses: awalsh128/cache-apt-pkgs-action@acb598e5ddbc6f68a970c5da0688d2f3a9f04d05 # v1.6.0
        with:
          packages: libdrm-dev libdrm-amdgpu1

      - name: 拉取依赖
        run: cargo fetch

      - name: 单元测试
        run: cargo test


  publish:
    runs-on: ubuntu-latest
    needs: [test, release]
    if: needs.release.outputs.core
    steps:
      - name: 检出代码
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          ref: ${{ github.event.pull_request.head.ref || github.ref_name }}
          repository: ${{ github.event.pull_request.head.repo.full_name || github.repository }}

      - name: 设置 Rust 工具链
        uses: dtolnay/rust-toolchain@stable

      - name: 设置 Rust 缓存
        uses: swatinem/rust-cache@f13886b937689c021905a6b90929199931d60db1 # v2.8.1
        with:
          prefix-key: 'puniyu_system_info'

      - name: 发布
        run: |
          cargo publish -p puniyu_system_info
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_API_TOKEN }}

  build:
    needs: release
    if: needs.release.outputs.node
    uses: ./.github/workflows/build.yaml
    
  publish-npm:
    runs-on: ubuntu-latest
    needs: [ release, test, build ]
    steps:
      - name: 获取token
        uses: actions/create-github-app-token@67018539274d69449ef7c02e8e71183d1719ab42 # v2.1.4
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: 下载npm包
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6
        with:
          name: "npm-package"
          path: system_info_node

      - name: 下载构建产物
        uses: actions/download-artifact@018cc2cf5baa6db3ef3c5f8a56943fffe632ef53 # v6
        with:
          pattern: system-info-node*
          path: system_info_node/artifacts

      - name: 设置pnpm
        uses: pnpm/action-setup@41ff72655975bd51cab0327fa583b6e92b6d3061 # v4.2.0
        with:
          version: 10.22.0

      - name: 发布npm包
        run: |
          pnpm install
          pnpm config set provenance true
          pnpm config set registry https://registry.npmjs.org/
          echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
          pnpm run create-npm-dirs
          pnpm run artifacts
          pnpm publish --access public
        working-directory: system_info_node
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: 上传Release
        uses: softprops/action-gh-release@5be0e66d93ac7ed76da52eca8bb058f665c3a5fe # v2.4.2
        with:
          token: ${{ steps.app-token.outputs.token }}
          files: |
            system_info_node/artifacts/system-info-*/system-info*.node
          tag_name: ${{ needs.release.outputs.node_tag_name }}
